export declare class MiBandConstants {
    static readonly SERVICE_MIBAND = "fee0";
    static readonly SERVICE_MIBAND2 = "fee1";
    static readonly SERVICE_HEART_RATE = "180d";
    static readonly SERVICE_IMMEDIATE_ALERT = "1802";
    static readonly SERVICE_DEVICE_INFO = "180a";
    static readonly SERVICE_BATTERY = "180f";
    static readonly CHAR_AUTH = "ff01";
    static readonly CHAR_HEART_RATE_MEASURE = "2a39";
    static readonly CHAR_HEART_RATE_DATA = "2a37";
    static readonly CHAR_STEPS = "ff06";
    static readonly CHAR_ACTIVITY_DATA = "ff04";
    static readonly CHAR_NOTIFICATION = "ff03";
    static readonly CHAR_DEVICE_INFO = "ff01";
    static readonly CHAR_BATTERY = "ff0c";
    static readonly CHAR_TIME = "ff0a";
    static readonly CHAR_USER_INFO = "ff04";
    static readonly CHAR_CONTROL_POINT = "ff05";
    static readonly CHAR_REALTIME_STEPS = "ff06";
    static readonly CHAR_ACTIVITY_DATA_NOTIFY = "ff07";
    static readonly CHAR_FIRMWARE_DATA = "ff08";
    static readonly CHAR_LE_PARAMS = "ff09";
    static readonly CHAR_DATE_TIME = "ff0a";
    static readonly CHAR_STATISTICS = "ff0b";
    static readonly CHAR_BATTERY_INFO = "ff0c";
    static readonly CHAR_TEST = "ff0d";
    static readonly CHAR_SENSOR_DATA = "ff0e";
    static readonly CHAR_PAIR = "ff0f";
    static readonly CHAR_VIBRATION = "ff10";
    static readonly CMD_AUTH_REQUEST = 1;
    static readonly CMD_AUTH_CONFIRM = 2;
    static readonly CMD_START_HEART_RATE_MANUAL = 21;
    static readonly CMD_STOP_HEART_RATE_MANUAL = 22;
    static readonly CMD_NOTIFICATION = 5;
    static readonly CMD_SET_TIME = 10;
    static readonly CMD_GET_STEPS = 6;
    static readonly CMD_GET_ACTIVITY = 4;
    static readonly CMD_SET_USER_INFO = 79;
    static readonly CMD_SET_FITNESS_GOAL = 16;
    static readonly CMD_VIBRATION = 8;
    static readonly CMD_FACTORY_RESET = 9;
    static readonly CMD_REBOOT = 12;
    static readonly RESPONSE_HEART_RATE = 16;
    static readonly RESPONSE_ACTIVITY_DATA = 4;
    static readonly RESPONSE_REALTIME_STEPS = 6;
    static readonly RESPONSE_AUTH_SUCCESS = 16;
    static readonly RESPONSE_AUTH_FAIL = 17;
    static readonly RESPONSE_AUTH_REQUEST_RANDOM_AUTH_NUMBER = 2;
    static readonly RESPONSE_AUTH_SEND_ENCRYPTED_AUTH_NUMBER = 3;
    static readonly CCCD_UUID = "2902";
    static readonly HEART_RATE_SERVICE_UUID = "180d";
    static readonly HEART_RATE_MEASUREMENT_UUID = "2a37";
    static readonly HEART_RATE_CONTROL_POINT_UUID = "2a39";
    static readonly DEVICE_INFORMATION_SERVICE_UUID = "180a";
    static readonly BATTERY_SERVICE_UUID = "180f";
    static readonly BATTERY_LEVEL_UUID = "2a19";
    static readonly MIBAND_NAME_PATTERNS: string[];
    static readonly AUTH_SECRET_KEY_LENGTH = 16;
    static readonly AUTH_RANDOM_KEY_LENGTH = 16;
    static readonly AUTH_SEND_KEY: number[];
    static readonly AUTH_REQUEST_RANDOM_AUTH_NUMBER: number[];
    static readonly AUTH_SEND_ENCRYPTED_AUTH_NUMBER: number[];
    static readonly ACTIVITY_TYPE_ACTIVITY = 1;
    static readonly ACTIVITY_TYPE_UNKNOWN_1 = 2;
    static readonly ACTIVITY_TYPE_UNKNOWN_2 = 3;
    static readonly ACTIVITY_TYPE_NONWEAR = 4;
    static readonly ACTIVITY_TYPE_UNKNOWN_3 = 5;
    static readonly ACTIVITY_TYPE_CHARGING = 6;
    static readonly NOTIFICATION_TYPE_SMS = 1;
    static readonly NOTIFICATION_TYPE_CALL = 2;
    static readonly NOTIFICATION_TYPE_EMAIL = 3;
    static readonly NOTIFICATION_TYPE_CHAT = 4;
    static readonly NOTIFICATION_TYPE_SOCIAL = 5;
    static readonly NOTIFICATION_TYPE_CALENDAR = 6;
    static readonly VIBRATION_SHORT: number[];
    static readonly VIBRATION_LONG: number[];
    static readonly VIBRATION_TRIPLE: number[];
    static readonly DEVICE_CAPABILITIES: {
        MI_BAND: {
            hasHeartRateSensor: boolean;
            hasStepCounter: boolean;
            hasCalorieTracking: boolean;
            hasDistanceTracking: boolean;
            hasSleepTracking: boolean;
            hasNotifications: boolean;
            hasBatteryInfo: boolean;
            hasFind: boolean;
            supportsAuth: boolean;
        };
        MI_BAND_2: {
            hasHeartRateSensor: boolean;
            hasStepCounter: boolean;
            hasCalorieTracking: boolean;
            hasDistanceTracking: boolean;
            hasSleepTracking: boolean;
            hasNotifications: boolean;
            hasBatteryInfo: boolean;
            hasFind: boolean;
            supportsAuth: boolean;
        };
        MI_BAND_3: {
            hasHeartRateSensor: boolean;
            hasStepCounter: boolean;
            hasCalorieTracking: boolean;
            hasDistanceTracking: boolean;
            hasSleepTracking: boolean;
            hasNotifications: boolean;
            hasBatteryInfo: boolean;
            hasFind: boolean;
            supportsAuth: boolean;
        };
        MI_BAND_4: {
            hasHeartRateSensor: boolean;
            hasStepCounter: boolean;
            hasCalorieTracking: boolean;
            hasDistanceTracking: boolean;
            hasSleepTracking: boolean;
            hasNotifications: boolean;
            hasBatteryInfo: boolean;
            hasFind: boolean;
            supportsAuth: boolean;
        };
        MI_BAND_5: {
            hasHeartRateSensor: boolean;
            hasStepCounter: boolean;
            hasCalorieTracking: boolean;
            hasDistanceTracking: boolean;
            hasSleepTracking: boolean;
            hasNotifications: boolean;
            hasBatteryInfo: boolean;
            hasFind: boolean;
            supportsAuth: boolean;
        };
        MI_BAND_6: {
            hasHeartRateSensor: boolean;
            hasStepCounter: boolean;
            hasCalorieTracking: boolean;
            hasDistanceTracking: boolean;
            hasSleepTracking: boolean;
            hasNotifications: boolean;
            hasBatteryInfo: boolean;
            hasFind: boolean;
            supportsAuth: boolean;
        };
        MI_BAND_7: {
            hasHeartRateSensor: boolean;
            hasStepCounter: boolean;
            hasCalorieTracking: boolean;
            hasDistanceTracking: boolean;
            hasSleepTracking: boolean;
            hasNotifications: boolean;
            hasBatteryInfo: boolean;
            hasFind: boolean;
            supportsAuth: boolean;
        };
        MI_BAND_8: {
            hasHeartRateSensor: boolean;
            hasStepCounter: boolean;
            hasCalorieTracking: boolean;
            hasDistanceTracking: boolean;
            hasSleepTracking: boolean;
            hasNotifications: boolean;
            hasBatteryInfo: boolean;
            hasFind: boolean;
            supportsAuth: boolean;
        };
    };
    static readonly PROTOCOL_COMMANDS: {
        START_REALTIME_STEPS: number[];
        STOP_REALTIME_STEPS: number[];
        START_HEART_RATE: number[];
        STOP_HEART_RATE: number[];
        FETCH_ACTIVITY_DATA: number[];
        SET_FITNESS_GOAL: number[];
        FIND_DEVICE: number[];
        SEND_NOTIFICATION: number[];
        SET_TIME: number[];
        SET_USER_INFO: number[];
    };
    static readonly ERROR_CODES: {
        SUCCESS: number;
        FAILURE: number;
        INVALID_PARAMETER: number;
        NOT_SUPPORTED: number;
        AUTH_REQUIRED: number;
        TIMEOUT: number;
        BUSY: number;
    };
    static readonly MAX_PACKET_SIZE = 20;
    static readonly AUTH_PACKET_SIZE = 18;
    static readonly USER_INFO_PACKET_SIZE = 20;
    static readonly TIMEOUTS: {
        CONNECTION: number;
        AUTHENTICATION: number;
        COMMAND_RESPONSE: number;
        HEART_RATE_MEASUREMENT: number;
        DATA_FETCH: number;
    };
    static readonly DEFAULTS: {
        FITNESS_GOAL: number;
        USER_WEIGHT: number;
        USER_HEIGHT: number;
        USER_AGE: number;
        USER_GENDER: number;
    };
}
